### ISSUE TITLE
iOS session not starting

### ISSUE THREAD

**Issue by raymatos** [testfairy/testfairy-cordova-plugin#10]
Followed all the directions, still not seeing the any sessions for iOS.  Also for android not getting any video, the videos are blank.

**Comment by vijaysharm** [comment]
Please try version 2.0.0 of the plugin, and reopen the ticket if issue continues.

**Comment by shawns582** [comment]
Is this issue actually resolved? I am having the same problems with v2.0.9  - no iOS sessions and android videos are blank or show the splashscreen
