### ISSUE TITLE
iPhone6 crash on begin()

### ISSUE THREAD

**Issue by emc2spider** [testfairy/testfairy-cordova-plugin#11]
I have updated the plugin with the latest __SDK Version 1.5.6__ and now the app is crashing when installed on iPhone 6+ and 6s, thought it might have to do with iOS version but after testing on iPhone 5 and 5c with iOS 8.4 and 9.1 it doesn't seem to be related to the operating system but the actual device.

Also removed the Testfairy `begin()` code and the app worked fine on all devices. Does anyone have an idea how to solve this?

**Comment by gmegidish** [comment]
Can you please provide a stacktrace so we can investigate this with you?

**Comment by vijaysharm** [comment]
Please try version 2.0.0 of the plugin, and reopen the ticket if issue continues.

**Comment by faizr** [comment]
I am having the same issue, even with version 2.0.0. Any updates?

**Comment by vijaysharm** [comment]
Hi @faizr. Thanks for letting us know. Do you have any more information on reproducing this issue? I have just tried it with a brand new project with plugin v2.0.4, corodova 6.1.1, running on a simulator v9.3?
