### ISSUE TITLE
failureCallback is undefined in testfairy.js

### ISSUE THREAD

**Issue by mansimransingh** [testfairy/testfairy-cordova-plugin#12]
failureCallback is undefined in testfairy.js

https://github.com/testfairy/testfairy-cordova-plugin/blob/master/www/testfairy.js#L35

Fixed in: https://github.com/testfairy/testfairy-cordova-plugin/pull/13

**Comment by mansimransingh** [comment]
https://github.com/testfairy/testfairy-cordova-plugin/pull/13

**Comment by pniebrzydowski** [comment]
This issue still exists. If an appToken is not passed in correctly, it flows into the `else` block and an error throws and crashes the whole app because `failureCallback` is never defined in the file.

```
ReferenceError: failureCallback is not defined
    at TestFairy.begin ((index):3401:3)
```
