### ISSUE TITLE
Visual Comparison reports with this plugin?

### ISSUE THREAD

**Issue by emcniece** [testfairy/testfairy-cordova-plugin#17]
I see in the [example on the home page](https://testfairy.com/images/screenshot-screens.jpg) that Android Activities are available for visual comparison. 

1. Is it possible to get this with Cordova apps since they're webview?
1. Does this work for iOS too?

**Comment by vijaysharm** [comment]
Hi @emcniece We do support this feature on both iOS and Android. It should also work for Cordova. Please let me know if you can't find it.
