### ISSUE TITLE
hideWebViewElements not working

### ISSUE THREAD

**Issue by BassamHabash** [testfairy/testfairy-cordova-plugin#18]
Hello @vijaysharm  !

I'm using a plugin 2.1.8 in ionic1 project , and try to make :
TestFairy.hideWebViewElements("label#search-feild");
but isn't work ( not cover field  by black color.

test it in ios and android

Thanks.

**Comment by vijaysharm** [comment]
Hi @BassamHabash what is `label` in this case? is this a html element?

Also, unfortunately we do not support this feature on Android.

**Comment by BassamHabash** [comment]
Hi @vijaysharm
label is dom element that use in directive 
<label id ="search-feild" ( other attribute ) ></label>

also i'm trying to add it to your plugin by add:
else if ("hideWebViewElements".equals(action)) {
			String key = args.optString(0);
			TestFairy.hideView(key);
		} 

to CDVTestFairy.java

**Comment by BassamHabash** [comment]
Hi @vijaysharm 

the plugin work with me on ios , but not working on android , as you say , cases functionality for hide web view element not supported .
Thanks .
