### ISSUE TITLE
Xcode warning: "Null passed to a callee that requires a non-null argument"

### ISSUE THREAD

**Issue by mgatto** [testfairy/testfairy-cordova-plugin#20]
This occurs in CDVTestFairy.m:43:46

I've not observed any runtime errors, but would like to not have any compiler warnings.

`CLLocation *location = [[CLLocation alloc] initWithCoordinate:CLLocationCoordinate2DMake ([[coord objectForKey:@"latitude"] doubleValue], [[coord objectForKey:@"longitude"] doubleValue])  altitude:[[coord objectForKey:@"altitude"] longValue]  horizontalAccuracy:[[coord objectForKey:@"accuracy"] longValue] verticalAccuracy:[[coord objectForKey:@"altitudeAccuracy"] doubleValue] timestamp:nil];
`

Thanks.

**Comment by vijaysharm** [comment]
Thanks @mgatto. I've pushed a fix for this, and will be included in the next release.

**Comment by mgatto** [comment]
Great. Thanks!
