### ISSUE TITLE
Missing versions in npmjs.com

### ISSUE THREAD

**Issue by andres-arista** [testfairy/testfairy-cordova-plugin#23]
When executing npm view com.testfairy.cordova-plugin, only versions up to 2.14.0 show up, this means 

`cordova plugin add com.testfairy.cordova-plugin`
and
`cordova plugin update com.testfairy.cordova-plugin`

will not bring the latest versions

**Comment by vijaysharm** [comment]
@andres-arista thanks for letting us know. it looks like something weird was happening on travis that failed pushing new versions. We'll be sure to have that looked at with the next release. Until then, i've manually released version 2.17.0
