### ISSUE TITLE
TestFairy.begin failed

### ISSUE THREAD

**Issue by tofra** [testfairy/testfairy-cordova-plugin#24]
![image](https://user-images.githubusercontent.com/1746173/66493685-c31e4880-eab6-11e9-8857-b29e87b8f718.png)

Any idea why?

**Comment by vijaysharm** [comment]
Hi @tofra thanks for the issue. Can you please give me more context? I tried adding the plugin to a new cordova and ionic project, and tested on both ios and Android and am not getting this error.

**Comment by tofra** [comment]
I can reproduce it, with angular 8 and ionic 4 install using: 
1) `ionic start test-app tabs --type=angular`
2) `ionic cordova plugin add com.testfairy.cordova-plugin`
3) Add the following code 
```
this.platform.ready().then(() => {
      TestFairy.setServerEndpoint('https://nevobo.testfairy.com');
      TestFairy.begin(this, 'apikey');
}
```
4) `ionic cordova prepare ios`


`ionic info` gives me:
```
Ionic:

   Ionic CLI                     : 5.4.4
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : 0.2.9 

System:

   NodeJS : v10.16.3
   npm    : 6.9.0
   OS     : macOS Mojave
```
Using iOS I have a "better" stacktrace:
![image](https://user-images.githubusercontent.com/1746173/67201350-600da980-f406-11e9-9f79-d3d89a6f601f.png)

**Comment by vijaysharm** [comment]
Hi @tofra I tried your exact steps, and I don't get the same thing as you, You can see the sample project here: https://github.com/vijaysharm/testfairy-ionic-test

when i run `ionic info` here's what i get:

```
Ionic:

   Ionic CLI                     : 5.2.3
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Volumes/Storage/programming/android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.2
   NodeJS            : v12.2.0 (/Users/vsharma/.nvm/versions/node/v12.2.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.1 Build version 11A1027
```

I see from the stacktrace that the error seems to happen on line 31 in `www/testfairy.js` which I assume is this line: https://github.com/testfairy/testfairy-cordova-plugin/blob/master/www/testfairy.js#L30

I don't see any complex object that would cause a cyclical issue with `JSON.stringify`.

I can try to upgrade to the latest version (5.4.4) of the CLI if that makes a difference, but if there's any more information you have, that could help me reproduce this, I'd appreciate it.

**Comment by tofra** [comment]
I found it! The mistake I made was `TestFairy.begin(this, 'apikey');` should be `TestFairy.begin('apikey');` (without the **this**). 
The **this** is _not_ needed in ionic/cordova environment.

Thanks for your prompt help!! I really appreciate it! Now I need to get my trial extended to be able to test it.

**Comment by vijaysharm** [comment]
ah! i totally missed that! good catch! I'm glad things are working for you now. Always happy to help! Please do not hesitate to reach out to us if you have any other issue.
