### ISSUE TITLE
Supply feedback with shake not working

### ISSUE THREAD

**Issue by tofra** [testfairy/testfairy-cordova-plugin#26]
When I shake on android, the feedback form isn't shown on Android. It works fine on iOS.
I know it was working with version 2.20.3, but after upgrading to 2.21.2 is doesn't work anymore. I tried the latest version, and still doesn't work.

On a side note: I reverted back to 2.20.3, and now it also doesn't work. When I invoke `TestFairy.pushFeedbackController();` the feedback form is shown.

Any idea why it doesn't show the form on Android while shaking, but it is working on iOS?
I'm using platform Ionic 4.

**Comment by vijaysharm** [comment]
Hi @tofra, thanks for reaching out to us. We identified an issue that possibly caused this issue. Can you please try version 2.220.0 to see if this fixes the issue?

Thanks.

**Comment by tofra** [comment]
2.20.0? or 2.22.0?

**Comment by vijaysharm** [comment]
Sorry, I meant [2.22.1](https://github.com/testfairy/testfairy-cordova-plugin/releases/tag/2.22.1)

**Comment by tofra** [comment]
It works again with 2.22.1. 🎉 

But when I shake, I get the question to give feedback, after pressing yes the feedbackform shows. Then I go back, and shake again, then I don't get the question to give feedback again..
After force closing the app, then shaking again I do get the question again to give feedback. But after going back again, it doesn't work anymore.. I could be lucky, then it works two times, but the third time it doesn't work anymore.. (could not figure out a pattern)

**Comment by tofra** [comment]
PS. on the Android emulator the shaking doesn't work... (which is only a minor issue for me and other dev's)
