### ISSUE TITLE
Release the latest version in npm

### ISSUE THREAD

**Issue by Yura13** [testfairy/testfairy-cordova-plugin#29]
Could you please release the latest version(v.2.38.0) of the plugin in the npm registry?
Currently, in the npm registry released v.2.33.0.

**Comment by vijaysharm** [comment]
Hi @Yura13 Thanks for bringing this to our attention! Looks like our automated build system failed to notify us of the issue. I've just released [version 2.39.0](https://www.npmjs.com/package/com.testfairy.cordova-plugin/v/2.39.0) with the latest version of our SDK.

Thanks again for your help! 🍻
