### ISSUE TITLE
is there a capacitor plugin?

### ISSUE THREAD

**Issue by carlosen14** [testfairy/testfairy-cordova-plugin#30]
similar to cordova, but with small changes, mostly on how to install plugins.. 

btw, the ionic install instructions do not work anymore, ionic/cli changed `ionic plugin add com.testfairy.cordova-plugin`, `plugin` command does not exists.

**Comment by vijaysharm** [comment]
Thanks @carlosen14, I'll have a look at the ionic install instructions and update them. 

I can't speak to the capacitor plugin. Can you describe what's required from our plugin to support it? There was at least [one other person that mentioned](https://github.com/testfairy/testfairy-cordova-plugin/issues/28#issuecomment-637389888) installing the plugin as follows works for them:

```
npm i --save com.testfairy.cordova-plugin
```

**Comment by carlosen14** [comment]
hi @vijaysharm, here i saw this Ionic instructions [Dashboard > ADD SDK > IONIC](https://www.awesomescreenshot.com/video/3006682?key=674c3f0d4a0758e5be8e5f1b7c462bfd).

with capacitor `ionic cordova plugin add <npm-package>` does not work, because this is not a cordova project, it is a capacitor one.

well the main difference with plugins, is that `cordova plugin add` modifies the manifest and others xml files if required. but capacitor does not, and all this needs to be done by the user self.

but let me give it a try with the issue you pointed me. this is my bad, i googled for this but never searched here on issues.

thanks for your time really appretiate, if need something else i'll write back. :+1:

**Comment by vijaysharm** [comment]
Not a problem @carlosen14! Thank you for your help. I'll take a look into capacitor and see how, if possible, we can improve the installation process.
