### ISSUE TITLE
[PLCrashReport] TestFairy_plcrash_log_writer_init:366: Could not retreive parent process name: Operation not permitted

### ISSUE THREAD

**Issue by raymatos** [testfairy/testfairy-cordova-plugin#9]
i get the following error on device

```
[PLCrashReport] TestFairy_plcrash_log_writer_init:366: Could not retreive parent process name: Operation not permitted
```

**Comment by RoksaKosiv** [comment]
me too.

**Comment by chodges** [comment]
I concur.  I've been getting this error for a while.

**Comment by rsbydv** [comment]
is anyone know how to resolve this error??

**Comment by gmegidish** [comment]
It's a warning, does it affect you in any other way?
We have removed this warning, and it won't be in 1.7.6, to be released soon

**Comment by RoksaKosiv** [comment]
@gmegidish for me it doesn`t affect anything, it`s just annoying to see that in logs all the time. with a few warnings like that, one can miss important logs
